### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by yueyin1992** [cavan33/openbt_py#1]
Hi, 
Thanks for writing the python script to run BART. I'm new to BART and I've following the example branin but got the following error trying to call the predict function. It looks like the model is not fit. I wonder if you could provide some guidance. Thanks.

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[23], line 2
      1 # Calculate in-sample predictions
----> 2 fitp = m.predict(x, tc = 4)
      4 # Make a simple plot
      5 import matplotlib.pyplot as plt

File ~/opt/anaconda3/envs/flood/lib/python3.9/site-packages/openbt/openbt.py:305, in OPENBT.predict(self, X, q_lower, q_upper, **kwargs)
    303         pfile.write(str(param)+"\n")
    304 self._run_model(train=False)
--> 305 self._read_in_preds()
    306 # New: make things a bit more like R, and save attributes to a fit object:
    307 res = {}

File ~/opt/anaconda3/envs/flood/lib/python3.9/site-packages/openbt/openbt.py:328, in OPENBT._read_in_preds(self)
    326          mdraws.append(np.loadtxt(f))
    327 # print(mdraws[0].shape); print(len(mdraws))
--> 328 self.mdraws = np.concatenate(mdraws, axis=1) # Got rid of the transpose
    329 sdraws = []
    330 for f in sdraw_files:

File <__array_function__ internals>:180, in concatenate(*args, **kwargs)

ValueError: need at least one array to concatenate

**Comment by cavan33** [comment]
To be honest, I have no idea. Maybe I'd know with some more documentation,
but it's been a long time and I've kind of forgotten what I did. Sorry.
