### ISSUE TITLE
Add github actions and automatic pypi release upon tag

### ISSUE THREAD

**Issue by jdtuck** [cavan33/openbt_py#4]
I will be submitting a branch shortly on this, but will require setting up the pypi tokens. Can you do this or give me access to repository to help set this up. We are using this a lot on my lab and I would like to help maintain it and keep it updated. Additionally after release to pypi I can help develop the feedstock for conda.

**Comment by cavan33** [comment]
How do I give you access to the repo?

**Comment by jdtuck** [comment]
https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-access-to-your-personal-repositories/inviting-collaborators-to-a-personal-repository

**Comment by jdtuck** [comment]
got it, though it looks like you have access to settings only to set up the key. I will send you a message with the token. You add the secret under settings ->  secrets and variables -> actions. Under Repository secrets you add a New Repository Secret with the name PYPI_API_TOKEN and the token I will send you

**Comment by jdtuck** [comment]
Sent it to your e-mail
